

DROP TABLE IF EXISTS EMPLOYEE, ORGANISATION;

CREATE TABLE ORGANISATION (
  orgId INT AUTO_INCREMENT  PRIMARY KEY,
  orgName VARCHAR(20) NOT NULL
);

CREATE TABLE EMPLOYEE (
  empId INT AUTO_INCREMENT PRIMARY KEY,
  empName VARCHAR(20) NOT NULL,
  orgId INT,
  FOREIGN KEY(orgId) REFERENCES ORGANISATION(orgId)
);