
DROP TABLE IF EXISTS EMPLOYEE, EMPLOYEE_SKILLS, SKILL, PROFICIENCY, ORGANISATION;

CREATE TABLE ORGANISATION (
  orgId INT AUTO_INCREMENT  PRIMARY KEY,
  orgName VARCHAR(20) NOT NULL
);

CREATE TABLE PROFICIENCY (
  pId INT AUTO_INCREMENT  PRIMARY KEY,
  pName VARCHAR(20) NOT NULL
);

CREATE TABLE SKILL (
  sId INT AUTO_INCREMENT PRIMARY KEY,
  sName VARCHAR(20) NOT NULL
);

CREATE TABLE EMPLOYEE (
  empId INT AUTO_INCREMENT PRIMARY KEY,
  empName VARCHAR(20) NOT NULL,
  orgId INT,
  FOREIGN KEY(orgId) REFERENCES ORGANISATION(orgId)
);

CREATE TABLE EMPLOYEE_SKILLS (
  empId INT,
  sId INT,
  pId INT,
  PRIMARY KEY(empId, sId),
  FOREIGN KEY(pId) REFERENCES PROFICIENCY(pId)
);